### ISSUE TITLE
标签数据下标不对。

### ISSUE THREAD

**Issue by obouluh** [zhoujx4/DuEE#3]
您好！我在复现时碰到以下问题：
  File "run_ner.py", line 179, in <module>
    main()
  File "run_ner.py", line 161, in main
    eval_p, eval_r, eval_f1, eval_loss = evaluate(args, eval_iter, model, metric)
  File "run_ner.py", line 46, in evaluate
    n_infer, n_label, n_correct = metric.compute(batch["all_seq_lens"], preds, batch['all_labels'])
  File "/home/***/DuEE/metric/metric.py", line 74, in compute
    ] for sent_index in range(len(lengths))]
  File "/home/***/DuEE/metric/metric.py", line 74, in <listcomp>
    ] for sent_index in range(len(lengths))]
  File "/home/***/DuEE/metric/metric.py", line 73, in <listcomp>
    for index in labels[sent_index][:lengths[sent_index]]
KeyError: -1

打印出来label
[[-1 26 26 ... -1 -1 -1]
 [-1 26 26 ... -1 -1 -1]
 [-1 26 26 ... 26 26 26]
 ...
 [-1 26 26 ... -1 -1 -1]
 [-1 26 26 ... -1 -1 -1]
 [-1 26 26 ... -1 -1 -1]]

对比一下，除了与paddle的ChunkEvaluator类中，相关的下标不同以外
![image](https://user-images.githubusercontent.com/22076064/115832638-b0bff180-a445-11eb-9c09-ab9fbab66613.png)
好像没有其他区别。
请问有没有解决方法？

**Comment by zhoujx4** [comment]
你好，这里漏了一个1，bert预测的第一为【CLS】,没意义的，所以没必要保留哈






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhoujx4/DuEE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 下午3:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhoujx4/DuEE] 标签数据下标不对。 (#3)





 
您好！我在复现时碰到以下问题：
 File "run_ner.py", line 179, in 
 main()
 File "run_ner.py", line 161, in main
 eval_p, eval_r, eval_f1, eval_loss = evaluate(args, eval_iter, model, metric)
 File "run_ner.py", line 46, in evaluate
 n_infer, n_label, n_correct = metric.compute(batch["all_seq_lens"], preds, batch['all_labels'])
 File "/home//DuEE/metric/metric.py", line 74, in compute
 ] for sent_index in range(len(lengths))]
 File "/home//DuEE/metric/metric.py", line 74, in 
 ] for sent_index in range(len(lengths))]
 File "/home/***/DuEE/metric/metric.py", line 73, in 
 for index in labels[sent_index][:lengths[sent_index]]
 KeyError: -1
 
打印出来label
 [[-1 26 26 ... -1 -1 -1]
 [-1 26 26 ... -1 -1 -1]
 [-1 26 26 ... 26 26 26]
 ...
 [-1 26 26 ... -1 -1 -1]
 [-1 26 26 ... -1 -1 -1]
 [-1 26 26 ... -1 -1 -1]]
 
对比一下，除了与paddle的ChunkEvaluator类中，相关的下标不同以外
 
 好像没有其他区别。
 请问有没有解决方法？

**Comment by zhoujx4** [comment]
你好，这里漏了一个1，bert预测的第一为【CLS】,没意义的，所以没必要保留哈


因为在id2label_dict这个字典里面没有-1这个键，自然就报错了


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "zhoujx4/DuEE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 下午3:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhoujx4/DuEE] 标签数据下标不对。 (#3)





 
您好！我在复现时碰到以下问题：
 File "run_ner.py", line 179, in 
 main()
 File "run_ner.py", line 161, in main
 eval_p, eval_r, eval_f1, eval_loss = evaluate(args, eval_iter, model, metric)
 File "run_ner.py", line 46, in evaluate
 n_infer, n_label, n_correct = metric.compute(batch["all_seq_lens"], preds, batch['all_labels'])
 File "/home//DuEE/metric/metric.py", line 74, in compute
 ] for sent_index in range(len(lengths))]
 File "/home//DuEE/metric/metric.py", line 74, in 
 ] for sent_index in range(len(lengths))]
 File "/home/***/DuEE/metric/metric.py", line 73, in 
 for index in labels[sent_index][:lengths[sent_index]]
 KeyError: -1
 
打印出来label
 [[-1 26 26 ... -1 -1 -1]
 [-1 26 26 ... -1 -1 -1]
 [-1 26 26 ... 26 26 26]
 ...
 [-1 26 26 ... -1 -1 -1]
 [-1 26 26 ... -1 -1 -1]
 [-1 26 26 ... -1 -1 -1]]
 
对比一下，除了与paddle的ChunkEvaluator类中，相关的下标不同以外
 
 好像没有其他区别。
 请问有没有解决方法？

**Comment by obouluh** [comment]
@zhoujx4 已解决，谢谢
