### ISSUE TITLE
运行duee predict_cls出现的问题

### ISSUE THREAD

**Issue by bixingjian** [zhoujx4/DuEE#4]
运行:
```
CUDA_VISIBLE_DEVICES=2 python predict_cls.py --dataset=DuEE-Fin --event_type=enum -- max_len=256 --per_gpu_eval_batch_size=32 --model_name_or_path=/home/user/pretrained-model/chinese-roberta-wwm-ext-large --fine_tunning_model_path=./output/DuEE-Fin/enum/best_model.pkl --test_json=./data/DuEE-Fin/sentence/test.json
```

报错:
```predict_cls.py: error: the following arguments are required: --fine_tunning_model_path, --test_json```

**Comment by zhoujx4** [comment]
你好，你这个问题应该是参数的格式问题，而不是代码问题
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhoujx4/DuEE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月16日(星期天) 中午11:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhoujx4/DuEE] 运行duee predict_cls出现的问题 (#4)





 
运行:
 CUDA_VISIBLE_DEVICES=2 python predict_cls.py --dataset=DuEE-Fin --event_type=enum -- max_len=256 --per_gpu_eval_batch_size=32 --model_name_or_path=/home/user/pretrained-model/chinese-roberta-wwm-ext-large --fine_tunning_model_path=./output/DuEE-Fin/enum/best_model.pkl --test_json=./data/DuEE-Fin/sentence/test.json
 
报错:
 predict_cls.py: error: the following arguments are required: --fine_tunning_model_path, --test_json
